# Generated by Django 3.0.8 on 2020-08-31 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('uzytkownik', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dodatkowe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skladniki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=64, unique=True)),
                ('typ', models.PositiveSmallIntegerField(choices=[(5, 'Owoc'), (6, 'Owoce morza'), (0, 'brak wybranego typu'), (3, 'Mieso'), (4, 'Ryba'), (1, 'Warzywo'), (2, 'Przyprawa')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Zakupy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('zakonczone', models.BooleanField(default=False, null=True)),
                ('zakupy_id', models.CharField(max_length=200, null=True)),
                ('klient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pracaDyplomowaAplikacja.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='ZakupyElementy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField(blank=True, default=0, null=True)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pracaDyplomowaAplikacja.Customer')),
                ('zakupy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pracaDyplomowaAplikacja.Zakupy')),
            ],
        ),
        migrations.CreateModel(
            name='Przepis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=64, unique=True)),
                ('opis', models.TextField(blank=True, default='', null=True)),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='zdjecia')),
                ('data_dodania', models.DateField(auto_now_add=True)),
                ('edytowane', models.DateField(auto_now=True)),
                ('czas_przygotowania', models.DurationField(blank=True, default=0)),
                ('stopien_trudnosci', models.DecimalField(decimal_places=2, max_digits=4)),
                ('skladniki', models.ManyToManyField(through='pracaDyplomowaAplikacja.Dodatkowe', to='pracaDyplomowaAplikacja.Skladniki')),
            ],
        ),
        migrations.AddField(
            model_name='dodatkowe',
            name='przepis',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pracaDyplomowaAplikacja.Przepis'),
        ),
        migrations.AddField(
            model_name='dodatkowe',
            name='skladnik',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pracaDyplomowaAplikacja.Skladniki'),
        ),
    ]
