# Generated by Django 3.0.8 on 2020-10-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracaDyplomowaAplikacja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='przepis',
            name='krotki_opis',
        ),
        migrations.RemoveField(
            model_name='przepis',
            name='przygotowanie',
        ),
        migrations.RemoveField(
            model_name='przepis',
            name='skladniki_ilosc',
        ),
        migrations.AlterField(
            model_name='skladniki',
            name='typ',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Mieso'), (4, 'Ryba'), (6, 'Owoce morza'), (5, 'Owoc'), (2, 'Przyprawa'), (0, 'brak wybranego typu'), (1, 'Warzywo')], default=0),
        ),
    ]
