# Generated by Django 3.0.8 on 2020-08-31 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pracaDyplomowaAplikacja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skladniki',
            name='typ',
            field=models.PositiveSmallIntegerField(choices=[(0, 'brak wybranego typu'), (3, 'Mieso'), (5, 'Owoc'), (4, 'Ryba'), (1, 'Warzywo'), (2, 'Przyprawa'), (6, 'Owoce morza')], default=0),
        ),
        migrations.AlterField(
            model_name='zakupyelementy',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pracaDyplomowaAplikacja.Przepis'),
        ),
    ]
