# Generated by Django 3.0.8 on 2020-11-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracaDyplomowaAplikacja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='przepis',
            name='zweryfikowany',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='skladniki',
            name='typ',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Warzywo'), (5, 'Owoc'), (2, 'Przyprawa'), (3, 'Mieso'), (0, 'brak wybranego typu'), (4, 'Ryba'), (6, 'Owoce morza')], default=0),
        ),
    ]
