# Generated by Django 3.0.8 on 2020-10-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracaDyplomowaAplikacja', '0002_auto_20201028_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='przepis',
            name='krotki_opis',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='przepis',
            name='przygotowanie',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='przepis',
            name='skladniki_ilosc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='skladniki',
            name='typ',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Mieso'), (5, 'Owoc'), (2, 'Przyprawa'), (6, 'Owoce morza'), (4, 'Ryba'), (1, 'Warzywo'), (0, 'brak wybranego typu')], default=0),
        ),
    ]
