# Generated by Django 3.0.8 on 2020-11-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracaDyplomowaAplikacja', '0003_auto_20201028_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='przepis',
            name='zweryfikowany',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='skladniki',
            name='typ',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Przyprawa'), (6, 'Owoce morza'), (3, 'Mieso'), (5, 'Owoc'), (4, 'Ryba'), (1, 'Warzywo'), (0, 'brak wybranego typu')], default=0),
        ),
    ]
