# Generated by Django 3.0.8 on 2020-11-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracaDyplomowaAplikacja', '0004_auto_20201106_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skladniki',
            name='typ',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Przyprawa'), (5, 'Owoc'), (3, 'Mieso'), (0, 'brak wybranego typu'), (4, 'Ryba'), (1, 'Warzywo'), (6, 'Owoce morza')], default=0),
        ),
    ]
